GET http://localhost:3000/ HTTP/1.1

###
DELETE http://localhost:3000/624a9748055d3d95b881e0eb HTTP/1.1

###
POST http://localhost:3000/ HTTP/1.1
content-type: application/json

{
	"Description": "Water Bill",
	"Amount":      150.00,
	"Tags":        ["water", "tax", "fixed"],
	"Type":        "EX"
}