GET http://localhost:3000/ HTTP/1.1

###
DELETE http://localhost:3000/624b6d1d2f09e07a3097a315 HTTP/1.1

###
POST http://localhost:3000/ HTTP/1.1
content-type: application/json

{
	"Description": "Water Bill",
	"Amount":      150.00,
	"Tags":        ["power"],
	"Type":        "EXPENSE"
}